   # This is a basic workflow to help you get started with Actions

name: First Cron Job

       # Controls when the workflow will run
on: [push]
  # Triggers the workflow every 8 am
  # schedule:
  #   - cron: "0 8 * * *"

     # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
      - name: Access Regression Test
        run: pwd
      - name: Install dependencies
        run: |
             python -m pip install --upgrade pip
             pip install -r /home/runner/work/platform-automation/platform-automation/requirements.txt
      - name: Run 'Content Recipes' Upload
        run: pytest tests/test_content_recipes.py --alluredir=allure-results --env_id=1 --clean-alluredir
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
          channel-id: 'C06Q8HCJ692'
          # For posting a simple plain text message
          slack-message: "Health Check - Content Recipe: ${{ job.status }}}}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}  
