run:
	pytest --browser chromium --env_id=1  --alluredir=allure_results --clean-alluredir
	#npx allure serve allure_results
# 	pytest 'tests/test_nanl_upload_video.py' --browser-channel chrome --env_id=1  --alluredir=allure_results
# 	--clean-alluredir --loop=10